name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemSerebriennikov/buildozer-action@v1
        id: buildozer
        with:
          save_buildozer_config: false
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Keshavam-Mobile-App
          path: bin/*.apk
